using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace my_project
{
    public partial class OrderReports : Form
    {
        public OrderReports()
        {
            InitializeComponent();
        }

        private void checkedListBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
            for (int i = checkedListBox1.Items.Count - 1; i >= 0; i--)
            {
                if (checkedListBox1.Items[i] != checkedListBox1.SelectedItem)
                    checkedListBox1.SetItemChecked(i, false);
            }
        }

        private void generatebtn_Click(object sender, EventArgs e)
        {
            tableLayoutPanel1.Controls.Clear();
            tableLayoutPanel1.ColumnStyles.Clear();
            tableLayoutPanel1.RowStyles.Clear();
            tableLayoutPanel1.ColumnCount = 0;
            tableLayoutPanel1.RowCount = 0;

            if (checkedListBox1.CheckedItems.Count > 0)
            {
                string selectedFilter = checkedListBox1.CheckedItems[0].ToString();

                switch (selectedFilter)
                {
                    case "Number of Orders Placed Per Customer":
                        DisplayOrdersPlacedPerCustomer();
                        break;
                    case "Total Revenue Generated By Each Book":
                        DisplayRevenueByEachBook();
                        break;
                    case "Total Revenue Generated By Each Customer":
                        DisplayRevenueByEachCustomer();
                        break;
                    case "Most Bought Book":
                        DisplayMostBoughtBook();
                        break;
                    case "Average Order Value Per Customer":
                        DisplayAverageOrderValuePerCustomer();
                        break;
                    case "Average Number of Items Per Order":
                        DisplayAverageNumberOfItemsPerOrder();
                        break;
                    default:
                        break;
                }

            }
        }

        private void DisplayOrdersPlacedPerCustomer()
        {
            tableLayoutPanel1.Controls.Clear();
            tableLayoutPanel1.ColumnStyles.Clear();
            tableLayoutPanel1.RowStyles.Clear();
            tableLayoutPanel1.RowCount = 0;

            List<OrdersData> orders = DataBase.Instance.GetNumberOfOrdersPerCustomer();

            tableLayoutPanel1.ColumnCount = 2;
            tableLayoutPanel1.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            tableLayoutPanel1.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            tableLayoutPanel1.Controls.Add(new Label { Text = "Customer Username", AutoSize = true, }, 0, 0);
            tableLayoutPanel1.Controls.Add(new Label { Text = "Number of Orders", AutoSize = true }, 1, 0);

            for (int i = 0; i < orders.Count; i++)
            {
                tableLayoutPanel1.RowCount++;
                tableLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.AutoSize));
                tableLayoutPanel1.Controls.Add(new Label { Text = orders[i].CustomerID, AutoSize = true }, 0, i + 1);
                tableLayoutPanel1.Controls.Add(new Label { Text = orders[i].NumberOfOrders.ToString(), AutoSize = true }, 1, i + 1);
            }
        }

        private void DisplayRevenueByEachBook()
        {

            tableLayoutPanel1.Controls.Clear();
            tableLayoutPanel1.ColumnStyles.Clear();
            tableLayoutPanel1.RowStyles.Clear();
            tableLayoutPanel1.RowCount = 0;
            List<OrdersData> orders = DataBase.Instance.GetRevenueByEachBookNotReturned();

            tableLayoutPanel1.Controls.Add(new Label { Text = "Book Title", AutoSize = true,  }, 1, 0);
            tableLayoutPanel1.Controls.Add(new Label { Text = "Book ISBN", AutoSize = true,  }, 0, 0);
            tableLayoutPanel1.Controls.Add(new Label { Text = "Revenue", AutoSize = true,}, 2, 0);

            for (int i = 0; i < orders.Count; i++)
            {
                tableLayoutPanel1.Controls.Add(new Label { Text = orders[i].BookTitle, AutoSize = true }, 1, i+1);
                tableLayoutPanel1.Controls.Add(new Label { Text = orders[i].BookISBN, AutoSize = true }, 0, i+1);
                tableLayoutPanel1.Controls.Add(new Label { Text = orders[i].Revenue.ToString(), AutoSize = true }, 2, i+1);
            }
        }

        private void DisplayRevenueByEachCustomer()
        {
            tableLayoutPanel1.Controls.Clear();
            tableLayoutPanel1.ColumnStyles.Clear();
            tableLayoutPanel1.RowStyles.Clear();
            tableLayoutPanel1.RowCount = 0;

            List<OrdersData> orders = DataBase.Instance.GetRevenueByEachCustomer();

            tableLayoutPanel1.Controls.Add(new Label { Text = "Customer Username", AutoSize = true,  }, 0, 0);
            tableLayoutPanel1.Controls.Add(new Label { Text = "Revenue", AutoSize = true,  }, 1, 0);


            for (int i = 0; i < orders.Count; i++)
            {
                tableLayoutPanel1.Controls.Add(new Label { Text = orders[i].CustomerID, AutoSize = true }, 0, i+1);
                tableLayoutPanel1.Controls.Add(new Label { Text = orders[i].Revenue.ToString(), AutoSize = true }, 1, i+1);
            }
        }

        private void DisplayMostBoughtBook()
        {
            tableLayoutPanel1.Controls.Clear();
            tableLayoutPanel1.ColumnStyles.Clear();
            tableLayoutPanel1.RowStyles.Clear();
            tableLayoutPanel1.RowCount = 0;

            List<OrdersData> mostBoughtBooks = DataBase.Instance.GetMostBoughtBook();

            tableLayoutPanel1.Controls.Add(new Label { Text = "Book ISBN", AutoSize = true, }, 0, 0);
            tableLayoutPanel1.Controls.Add(new Label { Text = "Book Title", AutoSize = true, }, 1, 0);
            tableLayoutPanel1.Controls.Add(new Label { Text = "Purchase Count", AutoSize = true, }, 2, 0);

            if (mostBoughtBooks.Count > 0)
            {
                tableLayoutPanel1.Controls.Add(new Label { Text = mostBoughtBooks[0].BookISBN, AutoSize = true }, 0, 1);
                tableLayoutPanel1.Controls.Add(new Label { Text = mostBoughtBooks[0].BookTitle, AutoSize = true }, 1, 1);
                tableLayoutPanel1.Controls.Add(new Label { Text = mostBoughtBooks[0].PurchaseCount.ToString(), AutoSize = true }, 2, 1);
            }
        }

        private void DisplayAverageOrderValuePerCustomer()
        {
            List<OrdersData> orders = DataBase.Instance.GetAverageOrderValuePerCustomer();

            tableLayoutPanel1.Controls.Clear();
            tableLayoutPanel1.ColumnStyles.Clear();
            tableLayoutPanel1.RowStyles.Clear();
            tableLayoutPanel1.RowCount = 0;

            tableLayoutPanel1.Controls.Add(new Label { Text = "Customer ID", AutoSize = true, }, 0, 0);
            tableLayoutPanel1.Controls.Add(new Label { Text = "Average Order Value", AutoSize = true,  }, 1, 0);

            for (int i = 0; i < orders.Count; i++)
            {
                tableLayoutPanel1.Controls.Add(new Label { Text = orders[i].CustomerID, AutoSize = true }, 0, i+1);
                tableLayoutPanel1.Controls.Add(new Label { Text = orders[i].AverageOrderValue.ToString("C"), AutoSize = true }, 1, i+1);
            }
        }

        private void DisplayAverageNumberOfItemsPerOrder()
        {
            double averageNumberOfItems = DataBase.Instance.GetAverageNumberOfItemsPerOrder();

            tableLayoutPanel1.Controls.Clear();
            tableLayoutPanel1.ColumnStyles.Clear();
            tableLayoutPanel1.RowStyles.Clear();
            tableLayoutPanel1.RowCount = 0;

            tableLayoutPanel1.Controls.Add(new Label { Text = "Average Number of Items Per Order", AutoSize = true, }, 0, 0);

            tableLayoutPanel1.Controls.Add(new Label { Text = averageNumberOfItems.ToString(), AutoSize = true }, 0, 1);
        }

        private void tableLayoutPanel1_Paint(object sender, PaintEventArgs e)
        {

        }
    }
}
